var branchCarouselA = "<div id='branchesCarousel' class='carousel slide' data-ride='carousel'><ol class='carousel-indicators'><li data-target='#branchesCarousel' data-slide-to='0' class='active'></li><li data-target='#branchesCarousel' data-slide-to='1'></li></ol><div class='carousel-inner'><div class='item active' id='slideBranch1'><a href='branches/branchAr.php'><div id='arkadia' class='thumbnail'></div></a><a href='branches/branchBe.html'><div id='bello' class='thumbnail'></div></a><a href='branches/branchCa.html'><div id='calasanz' class='thumbnail'></div></a><a href='branches/branchCe.html'><div id='centro' class='thumbnail'></div></a></div><div class='item' id='slideBranch2'><a href='branches/branchOl.html'><div id='olaya' class='thumbnail'></div></a><a href='branches/branchPo.html'><div id='poblado' class='thumbnail'></div></a><a href='branches/branchIt.html'><div id='itagui' class='thumbnail'></div></a></div></div><a class='left carousel-control' href='#branchesCarousel' data-slide='prev'><span class='glyphicon glyphicon-chevron-left'></span><span class='sr-only'>Previous</span></a><a class='right carousel-control' href=#branchesCarousel' data-slide='next'><span class='glyphicon glyphicon-chevron-right'></span><span class='sr-only'>Next</span></a></div>";

function displayAntioquia(){
    document.getElementById('branches').innerHTML = branchCarouselA;
}

var branchCarouselB = "<div id='branchesCarousel' class='carousel slide' data-ride='carousel'><ol class='carousel-indicators'><li data-target='#branchesCarousel' data-slide-to='0' class='active'></li><li data-target='#branchesCarousel' data-slide-to='1'></li><li data-target='#branchesCarousel' data-slide-to='2'></li><li data-target='#branchesCarousel' data-slide-to='3'></li></ol><div class='carousel-inner'><div class='item active' id='slideBranch1'><a href='branches/branchAd.html'><div id='administrativa' class='thumbnail'></div></a><a href='branches/branchCI.html'><div id='centrointer' class='thumbnail'></div></a><a href='branches/branchCed.html'><div id='cedritos' class='thumbnail'></div></a><a href='branches/branchCM.html'><div id='centromayor' class='thumbnail'></div></a></div><div class='item' id='slideBranch1'><a href='branches/branchCha.html'><div id='chapinero' class='thumbnail'></div></a><a href='branches/branchChi.html'><div id='chia' class='thumbnail'></div></a><a href='branches/branchMa.html'><div id='madelena' class='thumbnail'></div></a><a href='branches/branchMo.html'><div id='modelia' class='thumbnail'></div></a></div><div class='item' id='slideBranch1'><a href='branches/branchMu.html'><div id='multiplaza' class='thumbnail'></div></a><a href='branches/branchPA.html'><div id='plazamerica' class='thumbnail'></div></a><a href='branches/branchPC.html'><div id='plazacentral' class='thumbnail'></div></a><a href='branches/branchRe.html'><div id='restrepo' class='thumbnail'></div></a></div><div class='item' id='slideBranch2'><a href='branches/branchSo.html'><div id='soacha' class='thumbnail'></div></a><a href='branches/branchSu.html'><div id='suba' class='thumbnail'></div></a><a href='branches/branchUO.html'><div id='uniocci' class='thumbnail'></div></a></div></div><a class='left carousel-control' href='#branchesCarousel' data-slide='prev'><span class='glyphicon glyphicon-chevron-left'></span><span class='sr-only'>Previous</span></a><a class='right carousel-control' href=#branchesCarousel' data-slide='next'><span class='glyphicon glyphicon-chevron-right'></span><span class='sr-only'>Next</span></a></div>";

function displayCundinamarca(){
    document.getElementById('branches').innerHTML = branchCarouselB;
}