<?php
error_reporting(0);
@ini_set('display_errors', 0);
    $branchN = new BranchName();

    if(isset($_POST['btnArkadia'])){
        $branchN->setBranchN($_POST['arkadia']);
        $branchN->branchN();
    }
    if(isset($_POST['btnBello'])){
        $branchN->setBranchN($_POST['bello']);
        $branchN->branchN();
    }
    if(isset($_POST['btnCalasanz'])){
        $branchN->setBranchN($_POST['calasanz']);
        $branchN->branchN();
    }
    if(isset($_POST['btnCentro'])){
        $branchN->setBranchN($_POST['centro']);
        $branchN->branchN();
    }
    if(isset($_POST['btnOlaya'])){
        $branchN->setBranchN($_POST['olaya']);
        $branchN->branchN();
    }
    if(isset($_POST['btnPoblado'])){
        $branchN->setBranchN($_POST['poblado']);
        $branchN->branchN();
    }
    if(isset($_POST['btnItagüí'])){
        $branchN->setBranchN($_POST['itagui']);
        $branchN->branchN();
    }
    if(isset($_POST['btnAdministrativa'])){
        $branchN->setBranchN($_POST['administrativa']);
        $branchN->branchN();
    }
    if(isset($_POST['btnCentroInter'])){
        $branchN->setBranchN($_POST['centrointer']);
        $branchN->branchN();
    }
    if(isset($_POST['btnCedritos'])){
        $branchN->setBranchN($_POST['cedritos']);
        $branchN->branchN();
    }
    if(isset($_POST['btnCentroMayor'])){
        $branchN->setBranchN($_POST['centromayor']);
        $branchN->branchN();
    }
    if(isset($_POST['btnChapinero'])){
        $branchN->setBranchN($_POST['chapinero']);
        $branchN->branchN();
    }
    if(isset($_POST['btnChia'])){
        $branchN->setBranchN($_POST['chia']);
        $branchN->branchN();
    }
    if(isset($_POST['btnMadelena'])){
        $branchN->setBranchN($_POST['madelena']);
        $branchN->branchN();
    }
    if(isset($_POST['btnModelia'])){
        $branchN->setBranchN($_POST['modelia']);
        $branchN->branchN();
    }
    if(isset($_POST['btnMultiplaza'])){
        $branchN->setBranchN($_POST['multiplaza']);
        $branchN->branchN();
    }
    if(isset($_POST['btnPlazaAm'])){
        $branchN->setBranchN($_POST['plazamerica']);
        $branchN->branchN();
    }
    if(isset($_POST['btnPlazaCentral'])){
        $branchN->setBranchN($_POST['plazacentral']);
        $branchN->branchN();
    }
    if(isset($_POST['btnRestrepo'])){
        $branchN->setBranchN($_POST['restrepo']);
        $branchN->branchN();
    }
    if(isset($_POST['btnSoacha'])){
        $branchN->setBranchN($_POST['soacha']);
        $branchN->branchN();
    }
    if(isset($_POST['btnSuba'])){
        $branchN->setBranchN($_POST['suba']);
        $branchN->branchN();
    }
    if(isset($_POST['btnUniOcci'])){
        $branchN->setBranchN($_POST['uniocci']);
        $branchN->branchN();
    }


?>